# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable
# packages will be blocked from merging.            - name: Instrument pipeline
  # You may pin to the exact commit or the version.
  # uses: autometrics-dev/instrument-pipeline@142e4e6cbc109bb37c705daa856b6462689b3ef8
  uses: autometrics-dev/instrument-pipeline@v0.1.0
  with:            - name: Deploy to IBM Cloud Foundry
  # You may pin to the exact commit or the version.
  # uses: IBM/cloudfoundry-deploy@fcb5a74cb36e7cd0bfe9f9b5d9d57aab85d00bd1
  uses: IBM/cloudfoundry-deploy@v2.1
  with:
    # IBM Cloud API key
    IBM_CLOUD_API_KEY: 
    # IBM Cloud Foundry API endpoint
    IBM_CLOUD_CF_API: 
    # IBM Cloud Foundry organization name
    IBM_CLOUD_CF_ORG: 
    # IBM Cloud Foundry space name
    IBM_CLOUD_CF_SPACE: 
    # App Manifest file
    APP_MANIFEST_FILE: # optional, default is manifest.yml
    # App variables file
    APP_VARS_FILE: # optional
    # IBM Cloud Foundry resource group
    RESOURCE_GROUP: # optional
          
    # URL to the aggregation gateway, for example `http://localhost:9091`
    pushgateway: 
    # Type of the aggregation gateway, one of `prometheus`, `gravel`, or `zapier`. Currently only changes the url format in case of prometheus
    gatewaytype: # optional
    # Comma separated list of buckets for duration histogram, with or without the brackets []
    buckets: # optional
          
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

# If using a dependency submission action in this workflow this permission will need to be set to:
#
# permissions:
#   contents: write
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always
        #   fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
        #   retry-on-snapshot-warnings: true
